📝 [RUMF-1397] Use new init parameters in the doc
DataDog/browser-sdk pull request #1922
Opened 2023-01-06 14:58 UTC by bcaudan

## Motivation

Following #1917, document new parameters

## Changes

Document `sessionSampleRate`, `traceSampleRate` and `trackUserInteractions`

## Testing

N/A

---

I have gone over the [contributing](https://github.com/DataDog/browser-sdk/blob/main/CONTRIBUTING.md) documentation.

2023-01-10 15:35 UTC, BenoitZugmeyer commented on packages/rum/README.md
> +  trackUserInteractions: true,
<!-- Warning represent user-facing problems. If possible, it's great to follow this kind of comment with a suggestion.  -->
**🔨 warning:** ‏You changed the doc corresponding to code snippet to be used before v4.20.0 and v4.10.2. It should stay the same here.

<!-- Suggestions are specific requests to improve the subject under review. It is assumed that we all want to do what's best, so these comments are never dismissed as “mere suggestions”, but are taken seriously.  -->
**💬 suggestion:** ‏maybe add a similar section "before v4.30.0"

2023-01-10 15:35 UTC, BenoitZugmeyer commented on packages/logs/README.md
> -| `sampleRate`          | Number                                                                    | No       | `100`           | The percentage of sessions to track: `100` for all, `0` for none. On
<!-- Suggestions are specific requests to improve the subject under review. It is assumed that we all want to do what's best, so these comments are never dismissed as “mere suggestions”, but are taken seriously.  -->
**💬 suggestion:** ‏keep the deprecated option here, similarly to RUM docs?

2023-01-10 16:07 UTC, BenoitZugmeyer approved these changes

2023-01-10 17:51 UTC, rtrieu requested changes

2023-01-10 17:51 UTC, rtrieu commented on packages/rum/README.md
> +The `trackUserInteractions` and `trackFrustrations` parameters enable the automatic collection of user clicks in your application. **Sensitive and private data** contained on your pages may be includ
```suggestion
The `trackUserInteractions` and `trackFrustrations` parameters enable the automatic collection of user clicks in your application. **Sensitive and private data** contained in your pages may be included to identify the elements interacted with.
```
I believe "contained in" is more grammatically correct.

2023-01-10 17:51 UTC, rtrieu commented on packages/rum/README.md
> +The `trackUserInteractions` and `trackFrustrations` parameters enable the automatic collection of user clicks in your application. **Sensitive and private data** contained on your pages may be includ
```suggestion
The `trackUserInteractions` and `trackFrustrations` parameters enable the automatic collection of user clicks in your application. **Sensitive and private data** contained in your pages may be included to identify the elements interacted with.
```

2023-01-10 17:51 UTC, rtrieu commented on packages/rum/README.md
> +The `trackUserInteractions` and `trackFrustrations` parameters enable the automatic collection of user clicks in your application. **Sensitive and private data** contained on your pages may be includ
```suggestion
The `trackUserInteractions` and `trackFrustrations` parameters enable the automatic collection of user clicks in your application. **Sensitive and private data** contained in your pages may be included to identify the elements interacted with.
```

2023-01-12 16:04 UTC, rtrieu approved these changes

2023-01-12 16:04 UTC, merged