[logs] document beforeSend API
DataDog/browser-sdk pull request #664
Opened 2020-12-22 13:14 UTC by hdelaby

## Motivation

Document `beforeSend` API introduced by https://github.com/DataDog/browser-sdk/pull/644

## Changes

Docs

## Testing

---

I have gone over the [contributing](https://github.com/DataDog/browser-sdk/blob/master/CONTRIBUTING.md) documentation.

2020-12-22 13:21 UTC, bcaudan approved these changes
LGTM

2020-12-23 17:30 UTC, kayayarai requested changes

2020-12-23 17:30 UTC, kayayarai commented on packages/logs/README.md
> +If your Browser logs data contains sensitive information that need redacting, configure the Browser SDK to scrub sensitive sequences by using the `beforeSend` callback when you initialize the Browser
```suggestion
If your Browser logs contain sensitive information that needs redacting, configure the Browser SDK to scrub sensitive sequences by using the `beforeSend` callback when you initialize the Browser Log Collector.
```

2020-12-23 17:30 UTC, kayayarai commented on packages/logs/README.md
> +This callback function gives you access to every event collected by the Browser SDK before they get sent to Datadog.
```suggestion
The `beforeSend` callback function gives you access to each event collected by the Browser SDK before it is sent to Datadog, and lets you update commonly redacted properties.
```

2020-12-23 17:30 UTC, kayayarai commented on packages/logs/README.md
> +For example, redact email addresses from your web application URLs:
```suggestion
For example, to redact email addresses from your web application URLs:
```

2020-12-23 17:30 UTC, kayayarai commented on packages/logs/README.md
> +**Note**: The Browser SDK will ignore modifications made to event properties not listed above. Find out about all event properties on the [Browser SDK repository][5].
```suggestion
**Note**: The Browser SDK will ignore modifications made to event properties not listed above. For more information about event properties, see the [Browser SDK repository][5].
```

2020-12-28 13:22 UTC, BenoitZugmeyer commented
@kayayarai thank you for your review, I applied your suggestions. Could you check it out?

2021-01-04 16:48 UTC, kayayarai approved these changes
👍  for the docs

2021-01-11 10:34 UTC, merged