[rum] modified docs on simultaneous logging
DataDog/browser-sdk pull request #879
Opened 2021-06-02 13:27 UTC by hdelaby

## Motivation

* New feature
## Changes
* Modified docs to change the definition of `setHandler()` and the examples

## Testing

---

I have gone over the [contributing](https://github.com/DataDog/browser-sdk/blob/main/CONTRIBUTING.md) documentation.

2021-06-02 13:39 UTC, bcaudan approved these changes
👍

2021-06-02 23:56 UTC, jtappa requested changes

2021-06-02 23:56 UTC, jtappa commented on packages/logs/README.md
> +- or to not send logs at all (`silent`)
```suggestion
- send logs to the `console` and Datadog (`http`)
- send logs to the `console` only
- not send logs at all (`silent`)
```

2021-06-03 09:46 UTC, hdelaby commented
@jtappa if everything's good for you, we can merge :)

2021-06-04 15:48 UTC, jtappa approved these changes

2021-06-07 12:14 UTC, merged