📝 add `actionNameAttribute` initialization parameter
DataDog/browser-sdk pull request #923
Opened 2021-07-06 08:41 UTC by bcaudan

## Motivation

Document new initialization parameter
Related doc PR: https://github.com/DataDog/documentation/pull/11014

## Changes

- add new parameter
- fix dead link

## Testing

NA

---

I have gone over the [contributing](https://github.com/DataDog/browser-sdk/blob/main/CONTRIBUTING.md) documentation.

2021-07-06 08:42 UTC, BenoitZugmeyer approved these changes

2021-07-06 08:46 UTC, webNeat approved these changes

2021-07-07 14:48 UTC, jtappa requested changes

2021-07-07 14:48 UTC, jtappa commented on packages/rum/README.md
> +Specify your own attribute that will be used to name actions, cf [declaring a name for actions][9].
```suggestion
Specify your own attribute to be used to [name actions][9].
```

2021-07-07 15:42 UTC, jtappa approved these changes

2021-07-08 07:15 UTC, merged